### ISSUE TITLE
Implement Test: CreatePostController

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#106]
Unit tests should be implemented for the CreatePostController.

**Comment by orhungorkem** [comment]
Ok, I started implementing it.

**Comment by orhungorkem** [comment]
I implemented and opened pull request.

**Comment by irem-zeynep** [comment]
The [request](https://github.com/bounswe/2021SpringGroup3/pull/110) is approved and merged into the dev branch.
