### ISSUE TITLE
Implement API functionality: getCommunitiesByPublicity

### ISSUE THREAD

**Issue by schroscatt** [bounswe/2021SpringGroup3#113]
Please implement a getCommunitiesByPublicity api which runs with a "get" request and returns the communities based on the selected publicity.

**Comment by irem-zeynep** [comment]
### Implemented controller for getting communities by publicity.
The controller includes the GET method. 
Selection is done by parameter public = boolean.

I opened a [pull request](https://github.com/bounswe/2021SpringGroup3/pull/125) and it is merged to the dev branch.
