### ISSUE TITLE
Implement Test: Get Communities By Publicity

### ISSUE THREAD

**Issue by kiymetakdemir** [bounswe/2021SpringGroup3#121]
Can you implement a unit test for get communities by publicity function?

**Comment by irem-zeynep** [comment]
### Implemented controller for getting communities by publicity.
The controller includes the GET method. 
Selection is done by parameter public = boolean.

I opened a [pull request](https://github.com/bounswe/2021SpringGroup3/pull/125) to merge into dev. Please review.

**Comment by kiymetakdemir** [comment]
I reviewed the code. Good job! I am waiting for the other reviewers to merge.

**Comment by irem-zeynep** [comment]
### Implemented unit tests to check the functionality of the controller.
Tests specifically control the GET method named **getCommunitiesByPublicity**.

I opened a [pull request](https://github.com/bounswe/2021SpringGroup3/pull/131). I will wait for at least two approval. Please review.

**Comment by irem-zeynep** [comment]
Since we decided to use ObjectId instead of String for ids and we changed the URL of the controller, I updated the tests.

**Comment by irem-zeynep** [comment]
The request is approved and merged into dev.

**Comment by irem-zeynep** [comment]
_After more research on unit tests, some improvements should be made to the written tests, so I opened the issues again._

In tests, it is necessary to check that the methods of the services are called once and that no other methods are called.

**Comment by irem-zeynep** [comment]
I opened pull request and waiting for review

**Comment by irem-zeynep** [comment]
I added extra tests to do the necessary controls. My tests are reviewed in the [request](https://github.com/bounswe/2021SpringGroup3/pull/149) and it is merged into dev.
