### ISSUE TITLE
Research: Angular for Front-End 

### ISSUE THREAD

**Issue by schroscatt** [bounswe/2021SpringGroup3#129]
I created an Angular project for our front-end by following this [tutorial](https://www.baeldung.com/spring-boot-angular-web).
I created User and Profile classes, Add User components etc. 
One can successfully create a user entity and store in our database by using the front-end.
I also showed how to run the project and add components to my team.
However, do we agree on not using the Angular?

**Comment by Ufuk-Arslan** [comment]
We saw your Angular project in the meeting and it was really nice. Unfortunately, we will not be using Angular for this project. We have decided to use SpringBoot for the frontend aspects of this project. Thanks a lot for your effort tho, I know your code and newly learned skills will be useful both for yourself and for the team.

**Comment by schroscatt** [comment]
Dear Ufuk,
Thank you for your feedback!
You are right, It was helpful for me to learn and gain new aspects!
