### ISSUE TITLE
Arranging Slack channels according to current tasks

### ISSUE THREAD

**Issue by schroscatt** [bounswe/2021SpringGroup3#130]
Dear Ufuk,
Can you plase arrange our Slack channels according to our current tasks (such as front-end, deployment etc.) for us to communicate easier. This would also help us to find past works easily.

**Comment by Ufuk-Arslan** [comment]
Dear Sevde, 
I've updated our Slack workspace according to our tasks. Our team can use these channels to discuss the current tasks:
- **task-deployment-testing**
- **task-frontend**
- **task-milestone-report-2**

Thanks for reminding me, now I'm closing this issue.
