### ISSUE TITLE
Implement Test: getProfile

### ISSUE THREAD

**Issue by schroscatt** [bounswe/2021SpringGroup3#142]
Can you please implement the tests for getting profile by id functionality for both functions in Profile Service and Profile Controller?

**Comment by schroscatt** [comment]
I implemented the tests asked for. It successfully passed all test cases.
[see pull request](https://github.com/bounswe/2021SpringGroup3/pull/141)

**Comment by bekirkeldal** [comment]
I'm closing this issue because it seems reviewed and merged in the linked pull request. Thank you!
