### ISSUE TITLE
Implement test: updateProfile & setRandomPic

### ISSUE THREAD

**Issue by schroscatt** [bounswe/2021SpringGroup3#143]
Can you please implement tests for updating profile and setting random pic functionalities for functions both in Profile Service and Profile Controller?

**Comment by schroscatt** [comment]
I implemented the tests asked for. It successfully passed all the test cases. 
[see pull request](https://github.com/bounswe/2021SpringGroup3/pull/141)

**Comment by bekirkeldal** [comment]
I'm closing this issue because it seems reviewed and merged in the linked pull request. Thank you!
