### ISSUE TITLE
Create Docker file and Implement AWS Deployment

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#150]
We need to handle the following tasks:
- Conduct research on Docker.
- Create a Docker image for our practice app to be distributed among servers and teammates.
- Conduct research on AWS (Amazon Web Services).
- Create an account and boot up an AWS machine.
- Deploy the Docker code into that AWS machine.

The deadline for this issue is **9.6.2021 23:59**. If you have any questions, please ask them via comments or from the deployment/testing channel in Slack. *Good luck*.

**Comment by irem-zeynep** [comment]
During the meeting, we worked together on the deployment. @halilbaydar shared the screen, together we deployed the docker image created by him and @schroscatt into the AWS machine. In this way, **all members** were able to participate in the deployment process. We realized that some changes are needed in the app. When it's complete, we'll deploy it again and share the link.

**Comment by schroscatt** [comment]
We deployed the [project](http://34.238.122.101:8080/home).
You can check the functionalities and our user interface. It works since the first day we deployed. It haven't had error or crushed so far. It is so nice to see our project running successfully.
Thanks everyone for the great effort!
