### ISSUE TITLE
Changing return type of Universities Controller

### ISSUE THREAD

**Issue by orhungorkem** [bounswe/2021SpringGroup3#153]
Hi Bekir,

Could you please change the return type of your **GetUniversitiesController** as a list of strings instead of just strings? I could process that however it is safer to keep data processing in backend components.

**Comment by bekirkeldal** [comment]
Hi,

I started working on it. I will inform you when it's done.

**Comment by bekirkeldal** [comment]
I made the necessary changes. Please review from [here](https://github.com/bounswe/2021SpringGroup3/pull/155).

**Comment by orhungorkem** [comment]
It is reviewed, thank you.
