### ISSUE TITLE
Update wiki page and sidebar

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#16]
Update the [wiki page](https://github.com/bounswe/2021SpringGroup3/wiki) of our group and sidebar in it as discussed in this week's meeting.

**Comment by irem-zeynep** [comment]
I updated the wiki page to make it more descriptive and added the necessary links. @orhungorkem reviewed and provided feedback. You can check the home page from [here](https://github.com/bounswe/2021SpringGroup3/wiki).
