### ISSUE TITLE
Milestone Report 2: Overall Status

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#162]
The overall status section in the Milestone report should be filled in. You can access the Milestone report on the slack channel.

In this section try to answer the following questions:

- What did we research and what preparations did we make for Milestone 2?
- What did we do in this process?
- How far have we progressed?

If you have an additional topic or suggestion, feel free to add.

**Comment by kiymetakdemir** [comment]
Thanks for organizing the questions. I completed to work on it. Can you review please? You can find it in our shared document for the Milestone Report.

**Comment by irem-zeynep** [comment]
Overall Status is added to the [milestone 2](https://github.com/bounswe/2021SpringGroup3/blob/master/deliverables/M2_Report_Group3.pdf). I reviewed and it is very descriptive. You summarized the status very well.
