### ISSUE TITLE
Milestone Report 2: Challenges we met as a group 

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#163]
The challenges section in the Milestone report should be filled in. You can access the Milestone report on the corresponding Slack channel.

In this section, the challenges we faced as a team should be mentioned.

These challenges could be from any fields such as:

- Communication
- Working during the pandemic
- Learning the Spring Boot or MongoDB
- Implementation of API functionality
- Reviewing and merging code
- Configuration of the project
- Dockerization and Deployment
- Design and implementing frontend

Feel free to ask.

**Comment by bekirkeldal** [comment]
I finished writing this section of the milestone report. You can review it from [here](https://docs.google.com/document/d/1ffQ7aIZM_OQvQHrayGyjAKGUNFxykvfCu-cNf9kp1-w/edit#).

**Comment by irem-zeynep** [comment]
Challenges are reviewed and added to the Milestone 2. It can be accessed from [here](https://github.com/bounswe/2021SpringGroup3/blob/master/deliverables/M2_Report_Group3.pdf) under the Challenges section. 
We faced many challenges in practice-app development. You summarized them well. Thanks!
