### ISSUE TITLE
Milestone Report 2: List and Status of the Deliverables

### ISSUE THREAD

**Issue by bekirkeldal** [bounswe/2021SpringGroup3#164]
Please prepare a table for list and status of the deliverables of milestone 2. The link for the milestone report document is provided in the Slack channel.

**Comment by irem-zeynep** [comment]
I started to work. You can follow the progress from the docs. I'll let you know when it's done.

**Comment by bekirkeldal** [comment]
I checked the milestone report doc. List and status of the deliverables were added to the milestone report as a table. Everything seems fine, thank you!

**Comment by irem-zeynep** [comment]
The section is completed and reviewed by @bekirkeldal. İt can be accessed from [milestone 2](https://github.com/bounswe/2021SpringGroup3/blob/master/deliverables/M2_Report_Group3.pdf).
