### ISSUE TITLE
Milestone Report 2: Evaluation of the Status of Deliverables

### ISSUE THREAD

**Issue by bekirkeldal** [bounswe/2021SpringGroup3#165]
Please evaluate the status of deliverables in the milestone report. The link for the milestone report document is provided in the Slack channel.

**Comment by irem-zeynep** [comment]
You can follow the progress from the docs. I'll let you know when it's done.

**Comment by bekirkeldal** [comment]
I checked the milestone report doc. The evaluations were added to the report in a detailed and well-organized format. Thank you!

**Comment by irem-zeynep** [comment]
Evaluations are completed and reviewed by @bekirkeldal. It can be accessed from [milestone 2](https://github.com/bounswe/2021SpringGroup3/blob/master/deliverables/M2_Report_Group3.pdf).
