### ISSUE TITLE
Milestone Report 2: Introduction

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#166]
You need to write the **Introduction** part of the **Executive Summary** of our 2nd milestone report. You can mention these topics:
- The aim of the milestone report
- Brief explanation of our project
- Brief description of the job done since the last milestone

Deadline: **13.06.2021**

**Comment by Ufuk-Arslan** [comment]
Note that the **Introduction** part can also be called **Summary of the Project**.

**Comment by bekirkeldal** [comment]
I have completed writing the introduction part of the executive summary. I think I included the topics you suggested above. You can check it from [here](https://docs.google.com/document/d/1ffQ7aIZM_OQvQHrayGyjAKGUNFxykvfCu-cNf9kp1-w/edit).
