### ISSUE TITLE
Milestone Report 2: Table of Work Done by Each Member

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#167]
You should find **Table of Work Done by Each Member** section in the **Milestone Report 2** template shared in our Slack workspace. There you should find your name and fill in your **Contributions** column with the contributions you made after milestone 1. 

Here is a hint included in the Milestone 2 Group Deliverable description shared in moodle:

> Bad examples: “I attended to the lectures and group meetings” or “I designed project plan”.
> Good example: “Researched the Swagger API Development support tools with <X> (another team member) and prepared the infrastructure. The resulting API documentation can be seen at <URI> (URI of your API documentation). ”

Deadline: **13.06.2021 23:00**

**Comment by irem-zeynep** [comment]
We all completed the Table of Work Done by Each Member. You can review it from [milestone 2](https://github.com/bounswe/2021SpringGroup3/blob/master/deliverables/M2_Report_Group3.pdf).
