### ISSUE TITLE
Milestone Report 2: Project Plan

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#171]
We need to cover and list the previous work done by each member until now. We need to check the Github issues for our repository and document their assignees, durations, start dates, and end dates. 

We can use any tool we want to create the project plan. It should be a single PDF file and we need to include it in our 2nd Milestone Report. *Good Luck!*

Deadline **13.06.2021 23:00**

**Comment by irem-zeynep** [comment]
We started documenting the project plan for the practice-app using ProjectLibre.

**Comment by kiymetakdemir** [comment]
We completed working on the project plan. Uploaded pod, pdf file and also images. All of them can be accessed from [wiki page](https://github.com/bounswe/2021SpringGroup3/wiki/Project-Plan). We also added images to Milestone Report 2.

**Comment by irem-zeynep** [comment]
Completed and added to [m2 report](https://github.com/bounswe/2021SpringGroup3/blob/master/deliverables/M2_Report_Group3.pdf).
