### ISSUE TITLE
Milestone Report 2: RAM

### ISSUE THREAD

**Issue by orhungorkem** [bounswe/2021SpringGroup3#172]
Please provide a RAM ( Responsibility Assignment Matrix ) for Milestone 2. RAM should include each unit of work and indicate the people who are:

* Leader (L)
* Contributor (C)
* Reviewer (R)

for included tasks.

**Comment by irem-zeynep** [comment]
We started using Excel.

**Comment by kiymetakdemir** [comment]
We completed working on the RAM. We are adding it to the Milestone Report.

**Comment by irem-zeynep** [comment]
We created RAM for Milestone 2 and merged it with the previous ram. We uploaded it to the Wiki. Here is the [link](https://github.com/bounswe/2021SpringGroup3/wiki/Responsibility-Assignment-Matrix-(RAM)).

**Comment by orhungorkem** [comment]
Thank you, the classfication is obvious, roles are clear.
