### ISSUE TITLE
Milestone Report 2: API Documentation

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#173]
The API documentation should be added under the API Documentation section in the Milestone 2 report. You can access the Milestone report on the corresponding Slack channel.

We documented our API using Swagger. It can be accessed from the browser using the [link](http://34.238.122.101:8080/swagger-ui/#/).

The page should be converted to pdf or jpeg and added to the milestone report.  

Possible solutions:
- checking online tools
- taking ss of the screen 
- printing the screen. 

Feel free to ask.

**Deadline**:  13.06.2021 11:00 pm

**Comment by orhungorkem** [comment]
I am on it. Thanks for the hints.

**Comment by orhungorkem** [comment]
I obtained the documentation image in .pdf file and send it from Slack. After review, you can paste it into the report.

**Comment by irem-zeynep** [comment]
Thanks for adding the API documentation to our milestone report. It can be accessed from [here](https://github.com/bounswe/2021SpringGroup3/blob/master/deliverables/M2_Report_Group3.pdf), at the end of the file.
