### ISSUE TITLE
Creating Personal WikiPage

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#181]
You need to create a personal page for yourself. 

This page should include headers as follows:

- About
- Interests
- Programming Languages
- Contact

You can use the [template](https://github.com/bounswe/2021SpringGroup3/wiki/Personal-Wiki-Page-Template) to create it. Please see one of the personal pages listed on the wiki home page. 

**Deadline**: 15.10.2021

Welcome to the team! 🥳

**Comment by capslock35** [comment]
done
