### ISSUE TITLE
Reviewing and updating sequence diagram: Search Community

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#191]
[Sequence diagram](https://github.com/bounswe/2021SpringGroup3/wiki/Sequence-Diagrams): **Search Community** should be reviewed and updated based on the changes made on the class diagram and the requirements. 

 * [Updated class diagram](https://github.com/bounswe/2021SpringGroup3/wiki/Class-Diagram) 
 * [Requirements](https://github.com/bounswe/2021SpringGroup3/wiki/Requirements)
 
 _Changes should be reviewed by at least one group member._

**Deadline: 17.10.2021**

**Comment by kiymetakdemir** [comment]
I reviewed it and there is no change required. All methods still exist in class diagram.
