### ISSUE TITLE
Organizing Meetings Notes

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#196]
Meetings notes should be organized and documented as:
 * Group meetings
 * Backend meetings
 * Frontend meetings
 * Mobile meetings
 
These pages should be created and their links should be added to the sidebar & homepage.

**Deadline**: 31.10.2021

**Comment by irem-zeynep** [comment]
I organized meetings notes. Following pages are created:
 * [Group meetings](https://github.com/bounswe/2021SpringGroup3/wiki/Group-Meetings)
 * [Backend meetings](https://github.com/bounswe/2021SpringGroup3/wiki/Backend-Meetings)
 * [Frontend meetings](https://github.com/bounswe/2021SpringGroup3/wiki/Frontend-Meetings)
 * [Mobile meetings](https://github.com/bounswe/2021SpringGroup3/wiki/Mobile-Meetings)
 
 Added navigation links to sidebar and wiki homepage.
 Please Review @Ufuk-Arslan

**Comment by Ufuk-Arslan** [comment]
I've checked the templates and structure you've set for our meeting notes, I'm sure those will come in handy.
Thanks, well done!
