### ISSUE TITLE
Meeting Notes

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#197]
Could you please document the meeting notes for this week? 
[Here](https://github.com/bounswe/2021SpringGroup3/wiki/Meeting-%2311) is the wiki page you should use.

Deadline **09.11.2021**

**Comment by halilbaydar** [comment]
I kept the meeting notes and added to wiki.

**Comment by Ufuk-Arslan** [comment]
I have checked out the meeting notes and they were well done. Thanks!
