### ISSUE TITLE
Creating issue template: backend, frontend and  mobile bug reports

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#198]
Following issue templates should be created:

- Bug report for backend
- Bug report for frontend
- Bug report for mobile

Issue templates should include descriptions, well-organized fields, and default labels.
Corresponding YAML files should be created [here](https://github.com/bounswe/2021SpringGroup3/tree/master/.github/ISSUE_TEMPLATE).

**Deadline**: 02.11.2021

**Comment by irem-zeynep** [comment]
Issue templates are created. They can be found under the directory [`/github/ISSUE_TEMPLATE/`](https://github.com/bounswe/2021SpringGroup3/tree/master/.github/ISSUE_TEMPLATE)

Created templates:

> - [Backend Bug Report](https://github.com/bounswe/2021SpringGroup3/blob/master/.github/ISSUE_TEMPLATE/backendBug.yaml) 
> - [Frontend Bug Report](https://github.com/bounswe/2021SpringGroup3/blob/master/.github/ISSUE_TEMPLATE/frontendBug.yaml)
> - [Mobile Bug Report](https://github.com/bounswe/2021SpringGroup3/blob/master/.github/ISSUE_TEMPLATE/mobileBug.yaml)

These templates can now be seen as an option while [creating a new issue](https://github.com/bounswe/2021SpringGroup3/issues/new/choose). 

_Please review the templates and let me know if something should change. You may close the issue. @Ufuk-Arslan_

**Comment by Ufuk-Arslan** [comment]
I've reviewed the templates you have done. These will surely help us become more organized when reporting those bugs, and save us time figuring out the problems.
Thank you very much, and good job!
