### ISSUE TITLE
Design for Mobile: Login Page

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#199]
We should design the 'Login Page' for the mobile project.
You can find which fields the login page should contain from our [requirements 1.1.2. Login/Logout section](https://github.com/bounswe/2021SpringGroup3/wiki/Requirements#1-user-requirements).

**Deadline** 09.11.21

**Comment by irem-zeynep** [comment]
I initialized a spec for the backend and add **login** endpoint. 
You can review it from [here](https://github.com/bounswe/2021SpringGroup3/blob/backend/master/backend/resource/swagger.yaml), until it is deployed.

**Comment by irem-zeynep** [comment]
The login page is implemented and the [pull request](https://github.com/bounswe/2021SpringGroup3/pull/204) is opened.

**Comment by irem-zeynep** [comment]
The login page is designed and implemented. It is reviewed by @halilbaydar and merged.
