### ISSUE TITLE
Design for Web: Login Page

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#202]
**Login Page** should be designed and implemented for our web application. 
This page should contain fields that are described in the requirements [1.1.2. Login/Logout section](https://github.com/bounswe/2021SpringGroup3/wiki/Requirements#1-user-requirements).

These fields are:

> - username / email
> - password

_You should create a branch specific to this feature. Also, a merge request should be opened to let us review the changes. At least one team member should review the work._

**Deadline** 09.11.21

**Comment by Ufuk-Arslan** [comment]
I've done my work and opened my [pull request here](https://github.com/bounswe/2021SpringGroup3/pull/219), @irem-zeynep @utulb @jcbod could you please review my work?

**Comment by irem-zeynep** [comment]
> I've done my work and opened my [pull request here](https://github.com/bounswe/2021SpringGroup3/pull/219), @irem-zeynep @utulb @jcbod could you please review my work?

The design looks good! It is consistent with the requirements. 
We may leave the forget password part to the second milestone. Also as a reminder, we decided to use [this](https://material.io/resources/color/#!/?view.left=0&view.right=0&primary.color=3949AB) color theme.
Thanks! 🌟

**Comment by Ufuk-Arslan** [comment]
The pull request has been merged, I am closing this issue now.
