### ISSUE TITLE
Preparing Swagger YAML for backend

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#209]
Swagger YAML should be created for our API. 
The backend team will follow this spec during the implementation process.

Upload the Swagger to the directory _backend/resource._

**Deadline:** 9.11.2021

**Comment by irem-zeynep** [comment]
We completed

- Authentication Controller
- PostType Controller
- Post Controller

Please review the [spec](https://github.com/bounswe/2021SpringGroup3/blob/backend/master/backend/resource/swagger.yaml) @capslock35  @schroscatt 
You can use the [swagger editor](https://editor.swagger.io/).

**Comment by capslock35** [comment]
I think swagger documentation is good for the first milestone

**Comment by schroscatt** [comment]
Dear Irem and the team, thank you for the Swagger documentation. We will be working on it.
