### ISSUE TITLE
Design for Web: Confirmation Page

### ISSUE THREAD

**Issue by jcbod** [bounswe/2021SpringGroup3#213]
Design and implementation of the **Confirmation Page** for the web application. The page shall contain a confirmation code field as described in the [User Requirements - Registration - 1.1.1.2](https://github.com/bounswe/2021SpringGroup3/wiki/Requirements#1-user-requirements). 

_A new branch for this feature shall be created. A pull request shall be opened and the work shall be reviewed before merging process._

*Deadline:* 11.10.2021

**Comment by Ufuk-Arslan** [comment]
Thanks for your efforts. I have reviewed your pull request and merged it with our web dev branch.
