### ISSUE TITLE
Design for Web: Post Component

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#217]
Post Component should be designed and implemented for our web application.
This page should contain fields that are described in the requirements.

You should create a branch specific to this feature. Also, a merge request should be opened to let us review the changes. At least one team member should review the work.

Deadline 11.11.21

**Comment by Ufuk-Arslan** [comment]
I've done my work and opened my [pull request here](https://github.com/bounswe/2021SpringGroup3/pull/218), @utulb @jcbod could you please review my work?

**Comment by jcbod** [comment]
[Pull request](https://github.com/bounswe/2021SpringGroup3/pull/218) reviewed and resolved. Issue closed.
