### ISSUE TITLE
Design for Web: Profile view and edit components

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#220]
Profile view page and edit pages should be implemented for the web.
This page should contain fields that are described in the requirements.

You should create a branch specific to this feature. Also, a merge request should be opened to let us review the changes. At least one team member should review the work.

Deadline 12.11.21

**Comment by Ufuk-Arslan** [comment]
@jcbod @utulb I've implemented the pages, please review [here](https://github.com/bounswe/2021SpringGroup3/pull/252)

**Comment by utulb** [comment]
Page and component design is perfect. Therefore, I closing the issue.
