### ISSUE TITLE
Design for Web: Navigation Bar Component

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#223]
We should design the 'Navigation Bar Component' for the web project.
You may check out the navigation bars from our mockups.

- Logo button
- Home
-- Get communites
- Create Community
- Create Post
- Search input
- Direct messgaes
- Notifications
- Profile
-- Settings
-- Logout

Deadline 12.11.21

**Comment by jcbod** [comment]
Completed my work and opened a [pull request](https://github.com/bounswe/2021SpringGroup3/pull/245). Could you please review it?

**Comment by Ufuk-Arslan** [comment]
Well done mate! I have reviewed your pull request and now I'm closing this issue.
