### ISSUE TITLE
Documenting Frontend Meeting at 11.11.2021

### ISSUE THREAD

**Issue by jcbod** [bounswe/2021SpringGroup3#224]
Documenting the decisions taken during the frontend meeting in 11.11.2021 and uploading them to the project wiki.

**Comment by Ufuk-Arslan** [comment]
You can find the documentation of the meeting notes [here](https://github.com/bounswe/2021SpringGroup3/wiki/Fronetend-Meeting-%231).

**Comment by jcbod** [comment]
The documentation looks great! Thank you for your work.
