### ISSUE TITLE
Redesigning Swagger YAML for backend

### ISSUE THREAD

**Issue by kiymetakdemir** [bounswe/2021SpringGroup3#230]
[Swagger documentation](https://github.com/bounswe/2021SpringGroup3/blob/backend/master/backend/resource/swagger.yaml) should be redesigned and functionalities planned for Milestone 2 should be added as soon as possible.

**Comment by irem-zeynep** [comment]
The YAML file is updated and opened a pull request. Changes can be viewed from [here](https://github.com/bounswe/2021SpringGroup3/pull/232/files). 
Waiting for approval from @capslock35 and @schroscatt

**Comment by irem-zeynep** [comment]
It is approved by @capslock35 and merged to the _backend/master_ branch. It is converted to the JSON file which can be accessed from [here](https://github.com/bounswe/2021SpringGroup3/blob/backend/master/backend/resource/swagger.json).
