### ISSUE TITLE
Create a Github Action for automatic deployment

### ISSUE THREAD

**Issue by capslock35** [bounswe/2021SpringGroup3#239]

**Comment by capslock35** [comment]
Deploy action is created, we need secrets to be added before using it:
https://github.com/bounswe/2021SpringGroup3/actions/workflows/main.yml

**Comment by schroscatt** [comment]
Dear Kaan,
the Github action is very useful for our team. Thanks to you, everyone can deploy our code in a simple way.
Thank you for your effort.
