### ISSUE TITLE
Domain Analysis

### ISSUE THREAD

**Issue by bekirkeldal** [bounswe/2021SpringGroup3#24]
- Perform an analysis of the domain for the project.
- Prepare a table of common and missing features.

**Comment by Ufuk-Arslan** [comment]
We are preparing our analysis in a [google sheet](https://docs.google.com/spreadsheets/d/1F0yw3C0TNc0Iyll-20ZOkkwS5XEM545VcrPDmMdwqqg/edit?usp=sharing).

**Comment by orhungorkem** [comment]
I reviewed the analysis and it helped. Thanks!
