### ISSUE TITLE
Design for Web: About Community Component

### ISSUE THREAD

**Issue by jcbod** [bounswe/2021SpringGroup3#240]
Design and implementation of the **About Community Component** for the web application. The component shall contain a brief description of the community, member amount and creation date. 

_A new branch for this feature shall be created. A pull request shall be opened and the work shall be reviewed before merging process._

*Deadline:* 14.10.2021

**Comment by jcbod** [comment]
Completed my work and opened a [pull request](https://github.com/bounswe/2021SpringGroup3/pull/246). Could you please review it @Ufuk-Arslan @utulb ?

**Comment by Ufuk-Arslan** [comment]
I have reviewed your pull request and now this issue is over. Well done!
