### ISSUE TITLE
Design for Web: Create Community Component

### ISSUE THREAD

**Issue by jcbod** [bounswe/2021SpringGroup3#244]
Design and implementation of the **Create Community Component** for the web application. The component shall contain a form which takes the community name, topics list, description and privacy choice.

_A new branch for this feature shall be created. A pull request shall be opened and the work shall be reviewed before merging process._

*Deadline:* 14.10.2021

**Comment by jcbod** [comment]
Completed my work and opened a [pull request](https://github.com/bounswe/2021SpringGroup3/pull/249). Could you please review my work @Ufuk-Arslan @utulb ?

**Comment by Ufuk-Arslan** [comment]
Good job mate! I have reviewed the pull request and the issue is done.
