### ISSUE TITLE
[Bug]: Swagger UI Authorization header problem

### ISSUE THREAD

**Issue by capslock35** [bounswe/2021SpringGroup3#260]
### What happened?

Swagger UI does not allow authorization header to be sent without authorization

### Which version?

1.0.0

**Comment by irem-zeynep** [comment]
[Here](https://github.com/bounswe/2021SpringGroup3/commit/a2612a800b199a37875f3086fa028ada58b737fc#diff-ca51d35f0bc1577ee1e15278a0fe9519328bdce6f39a2a2838d72a67a56881a7) is the solution.
