### ISSUE TITLE
Web: Create deployment

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#277]
Please search about GitHub actions, then deploy our web dev branch.

Deadline: **16.11.2021**

**Comment by jcbod** [comment]
Deployed the application at https://jcbod.github.io/login using GitHub Pages. Please review.

**Comment by Ufuk-Arslan** [comment]
Looks great, thanks for the fast implementation, we really needed that! Now, I'm closing this issue.
