### ISSUE TITLE
Customer Presentation Notes

### ISSUE THREAD

**Issue by kiymetakdemir** [bounswe/2021SpringGroup3#279]
Customer presentation on 16.11.2021 should be documented. Received feedbacks during the meeting should be noted and documented.

**Comment by kiymetakdemir** [comment]
I created a wiki page for [Customer Presentations](https://github.com/bounswe/2021SpringGroup3/wiki/Customer-Presentations), future presentations can be also documented there. I documented the first presentation. Please review @irem-zeynep

**Comment by irem-zeynep** [comment]
I reviewed the [Customer Presentations](https://github.com/bounswe/2021SpringGroup3/wiki/Customer-Presentations) and It is well-organized and informative. We should proceed by paying attention to these notes. Thanks for taking note and documenting it!
