### ISSUE TITLE
Mobile: Design for pages under construction

### ISSUE THREAD

**Issue by kiymetakdemir** [bounswe/2021SpringGroup3#280]
A view should be designed and implemented for pages under construction. 

Pages under construction are:
* Chat
* Notifications
* Home
* Profile
* Settings

Deadline: 19.11.2021

**Comment by irem-zeynep** [comment]
I completed the implementation and opened [the pull request](https://github.com/bounswe/2021SpringGroup3/pull/283).
Please review @kiymetakdemir

**Comment by kiymetakdemir** [comment]
I reviewed the changes, branch is merged.
