### ISSUE TITLE
Milestone 1: Gathering Deliverables

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#284]
Mİlestone 1 deliverables should be added to the report. The link of the report is shared on the Slack _links-task-contents_ channel.
Deliverables:

- [x]  Requirements
- [x] UML Software Designs
- [x] Scenarios and Mockups
- [x] Project plan
- [x] Communication Plan
- [x] RAM
- [x] Milestone Review

**Comment by irem-zeynep** [comment]
I created the template for the milestone 1 report and added UML Software Designs. These designs are grouped as a class, use case, and sequence diagrams.

**Comment by kiymetakdemir** [comment]
I modified [project plan](https://github.com/bounswe/2021SpringGroup3/wiki/Responsibility-Assignment-Matrix-(RAM)), edited assignees and dates for the tasks. I added mobile part to [RAM](https://github.com/bounswe/2021SpringGroup3/blob/master/deliverables/RAM-CMPE451-M1.pdf). 
Both files are uploaded to Github, wiki pages are modified and screenshots added to milestone report.

**Comment by kiymetakdemir** [comment]
I added screenshot of [Communication Plan](https://github.com/bounswe/2021SpringGroup3/wiki/Communication-Plan) to milestone report.

**Comment by Ufuk-Arslan** [comment]
I have completed the Scenarios and Mockups section according to our [Scenarios and Mockups in our wiki](https://github.com/bounswe/2021SpringGroup3/wiki/Scenarios-&-Mockups).

**Comment by Ufuk-Arslan** [comment]
I added our [requirements](https://github.com/bounswe/2021SpringGroup3/wiki/Requirements) to the deliverables. Now every section of deliverables is done, thanks for everyone's efforts.
