### ISSUE TITLE
Milestone 1: Road Ahead

### ISSUE THREAD

**Issue by schroscatt** [bounswe/2021SpringGroup3#285]
Dear Ufuk, can you please document our road ahead for the Milestone Report 1? 
You can get help from our [future work presentation](https://www.canva.com/design/DAEv4f_aiCo/BJPwTi9o32ly4Kc6ZhiuBw/view?utm_content=DAEv4f_aiCo&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton).
Deadline: 20 November

**Comment by Ufuk-Arslan** [comment]
Dear Sevde, I wrote the **Road Ahead** section of our Milestone Report. I have also included the information you provided at future work presentation, thanks for that! Could you please review this section?

**Comment by schroscatt** [comment]
I checked before the submission. Thank you for your effort.
