### ISSUE TITLE
Milestone 1: Evaluation of the status of deliverables (backend)

### ISSUE THREAD

**Issue by kiymetakdemir** [bounswe/2021SpringGroup3#287]
Evaluation of the status of deliverables for backend should be written in Milestone 1. Its impact on our project plan also should be included.

**Comment by schroscatt** [comment]
I've written the evaluation of the status of deliverables for backend in the doc. Please check :)

**Comment by Ufuk-Arslan** [comment]
@schroscatt looks amazing.
