### ISSUE TITLE
Milestone 1: Evaluation of the status of deliverables (web)

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#289]
Evaluation of the status of deliverables for web should be written in Milestone 1. You can find our milestone 1 report from the links-task-content channel in our Slack workspace.

**Comment by utulb** [comment]
Evaluation of tools and processes for web has written in Milestone 1.

**Comment by Ufuk-Arslan** [comment]
I have read the section you wrote in the milestone report. It explains the tools that we used in our web project very well. It looks great!
