### ISSUE TITLE
Milestone 1: RAM

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#290]
Please document a RAM ( Responsibility Assignment Matrix ) for Milestone 1. 
RAM should include each unit of work and indicate the people who are:

- Leader (L)
- Contributor (C)
- Reviewer (R)

for included tasks.

Please categorize tasks as general, backend, mobile, and web.

**Deadline**: 20.11.2021

**Comment by Ufuk-Arslan** [comment]
I have documented the tasks assigned to the **Web team** in our RAM.

**Comment by irem-zeynep** [comment]
I documented the tasks for the team in general especially the week1&2.

**Comment by irem-zeynep** [comment]
RAM is completed and documented in [Milestone 1](https://github.com/bounswe/2021SpringGroup3/blob/master/deliverables/M1-Group3.pdf).
