### ISSUE TITLE
Milestone 1: List and Status of Deliverables (mobile)

### ISSUE THREAD

**Issue by kiymetakdemir** [bounswe/2021SpringGroup3#291]
Please prepare a table for list and status of the deliverables of mobile for Milestone 1. You can find the Milestone 1 document link on Slack.

**Comment by irem-zeynep** [comment]
I completed the list and status of deliverables for the team and added them to milestone report 2. You can review it using the link in our slack channel _#links-task-contents_

**Comment by Ufuk-Arslan** [comment]
@irem-zeynep list and status of deliverables for the mobile in our milestone report look great. Now I'm closing this issue.
