### ISSUE TITLE
Milestone 1: Evaluation of the status of the deliverables (mobile)

### ISSUE THREAD

**Issue by kiymetakdemir** [bounswe/2021SpringGroup3#292]
Evaluation of the status of deliverables for mobile should be written in Milestone 1. Its impact on our project plan also should be included.

**Comment by irem-zeynep** [comment]
I completed the task and added it to milestone report 2. You can review it using the link in our slack channel _#links-task-contents_

**Comment by Ufuk-Arslan** [comment]
I have reviewed the task. Thank you for your efforts.
