### ISSUE TITLE
Milestone 1: List and Status of Deliverables for team

### ISSUE THREAD

**Issue by kiymetakdemir** [bounswe/2021SpringGroup3#293]
List and Status of Deliverables for team should be prepared. Please consider that deliverables or mobile, web and backend will be prepared separately.

**Comment by irem-zeynep** [comment]
I completed the list and status of deliverables for the team and added them to milestone report 2. You can review it using the link in our slack channel _#links-task-contents_

**Comment by Ufuk-Arslan** [comment]
Looks nice. Thank you!
