### ISSUE TITLE
Mobile: Create Post

### ISSUE THREAD

**Issue by kiymetakdemir** [bounswe/2021SpringGroup3#295]
Please improve the code written before for create page. Some enhancements needed are:
* multiple fields from the same type should be added to a post
* date field should be added
* geolocation and map support

**Deadline: 04.12.2021**

**Comment by irem-zeynep** [comment]
I redesigned and implemented the `create post page`. 
Summary:

- Design is improved.
- Multiple fields from the same field type can be added to a post
- Date field type support is added
- The location input is improved with geolocation and map support

I opened a [pull request](https://github.com/bounswe/2021SpringGroup3/issues/251), please review.

**Comment by irem-zeynep** [comment]
The location object is updated based on the demand from the backend. 
PRs are approved and merged.
