### ISSUE TITLE
Mobile: Community Page

### ISSUE THREAD

**Issue by kiymetakdemir** [bounswe/2021SpringGroup3#296]
From the drawer, users should be directed to communities page. This page should list the communities of the user and also all communities in the app. When a community is clicked from the list, it should navigate to a page that displays the community details. 

**Deadline: 06.12.2021**

**Comment by irem-zeynep** [comment]
Implementation is completed. 
Details are explained in the [pull request](https://github.com/bounswe/2021SpringGroup3/pull/304). Please [review the difference](https://github.com/bounswe/2021SpringGroup3/pull/304/files).

**Comment by irem-zeynep** [comment]
PR is approved and merged to the _mobile/dev_.
