### ISSUE TITLE
Mobile: Post Detail Page

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#297]
The post detail page is currently running as a mock. 
Required enhancements:

- It should be developed to map the post detail information received from the backend.
- The view should include:
        1.  Body of the post 
        2.  Number of likes 
        3.  Like button
        4.  Name of the user
        5.  Image of the user
        6.  Community name

This page can be navigated from the create post page or from the home page when a post is clicked.

_At least one team member from the mobile team should review the implementation._

**Deadline**: 06.12.2021

**Comment by kiymetakdemir** [comment]
Pr is reviewed by @irem-zeynep and merged.
