### ISSUE TITLE
Identify and document non-functional requirements

### ISSUE THREAD

**Issue by jcbod** [bounswe/2021SpringGroup3#31]
Identify and document non-functional requirements under the non-functional requirements section.

**Comment by orhungorkem** [comment]
We examined the nonfunctional requirements and classified them with @kutaysaran . The documented requirements are available on wiki. Waiting for group confirmation.

**Comment by orhungorkem** [comment]
You can access the documentation [here.](https://github.com/bounswe/2021SpringGroup3/wiki/Requirements)
