### ISSUE TITLE
Documenting the Frontend Meeting on 07.12.2021

### ISSUE THREAD

**Issue by jcbod** [bounswe/2021SpringGroup3#311]
Documenting the key parts of the frontend meeting at 07.12.2021 and uploading the meeting notes to the wiki page.

**Comment by Ufuk-Arslan** [comment]
You can find today's frontend meeting notes [here](https://github.com/bounswe/2021SpringGroup3/wiki/Fronetend-Meeting-%232). Please review @jcbod

**Comment by jcbod** [comment]
Meeting notes are looking great! Issue closed.
