### ISSUE TITLE
Update Swagger documentation

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#313]
Dear Sevde,

We should update the Swagger documentation according to the changes in the location field for profiles and posts.

**Deadline** 12.08.21

**Comment by schroscatt** [comment]
I linked my pull request for the updated doc. Please review :)

**Comment by Ufuk-Arslan** [comment]
Looks awesome! This will help us be more clear while working on those features. Now I'm closing this issue.

**Comment by irem-zeynep** [comment]
The [changes](https://github.com/bounswe/2021SpringGroup3/pull/312/files) in the documentation are reviewed and approved. Merged to the _backend/master_.
