### ISSUE TITLE
Backend: Adding Like Count to Post Detail

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#322]
**Like Count** field should be added to the response of the `Get Post Detail` endpoint. 
You can reach the corresponding response model from the [Swagger](https://api.cmpegroupthree.store/docs/#/Post%20Controller/get%20postDetail).

**Deadline**: 11.12.2021

At least one team member should review the implementation. (📢 FYI @capslock35)

**Comment by schroscatt** [comment]
The change is done. Please see the linked pull request :)

**Comment by irem-zeynep** [comment]
Pull request is approved and merged. Thanks.
