### ISSUE TITLE
Backend: Adding Moderators and Members Fields to Community Detail

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#323]
The **Moderators** and **Members** fields should be added to the response of the [`Get Community Detail`](https://api.cmpegroupthree.store/docs/#/Community%20Controller/get%20communityDetail) endpoint. These fields should be lists that include ids, names, and photos of the users.

**Deadline**: 11.12.2021

At least one team member should review the implementation. (📢 FYI @capslock35)

**Comment by schroscatt** [comment]
The corresponding fields are added to the response and code is deployed.
