### ISSUE TITLE
Preparation of documentation regarding the feedback of the client meeting

### ISSUE THREAD

**Issue by halilbaydar** [bounswe/2021SpringGroup3#36]
Could you please document the feedback of the client meeting?

**Comment by emreboun** [comment]
Started to work on feedback documentation.

**Comment by emreboun** [comment]
Questions and answers are documented according to the feedback of customer at page [Customer Meeting #1](https://github.com/bounswe/2021SpringGroup3/wiki/Customer-Meeting-%231).

**Comment by irem-zeynep** [comment]
It is well documented and covers meeting notes that I took during the customer meeting. Thank you!
