### ISSUE TITLE
Implementation for Web: Create Post Page

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#362]
We should complete the backend connections and implement the Create Post page for our web application. The page shall be implemented using the designs added in #262 and you should use the fields given in our Swagger documentation.

We should use the react-google-map-picker package to select the location for the posts.

_A new branch for this feature shall be created. A pull request shall be opened and the work shall be reviewed before the merging process._

**Deadline**: 13.12.2021

**Comment by jcbod** [comment]
Post pages look great! Thank you for your work. Issue closed.
