### ISSUE TITLE
Implementation for Web: View Post Page

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#363]
We should complete the backend connections and implement the Post View page for our web application. The page shall be implemented using the designs added in #218 and you should use the fields given in our [Swagger documentation](https://github.com/bounswe/2021SpringGroup3/blob/backend/master/backend/resource/swagger.json). 

_A new branch for this feature shall be created. A pull request shall be opened and the work shall be reviewed before the merging process._

**Deadline**: 13.12.2021

**Comment by jcbod** [comment]
Pull request reviewed and merged. Closing Issue.
