### ISSUE TITLE
Mockup: Creating data type

### ISSUE THREAD

**Issue by orhungorkem** [bounswe/2021SpringGroup3#37]
An informative mockup needed for data type creation in web interface.
Deadline: 18.04.2021

**Comment by schroscatt** [comment]
I've designed the mockups about creating data type scenario.
There were 4 steps:
* Community Posts
* Community Data Types
* Creating Data Type
* Posting with the Data Type
[Creating Data Type Mockups](https://github.com/bounswe/2021SpringGroup3/wiki/Scenario-%233:-Creating-Data-Type#mockups)

**Comment by orhungorkem** [comment]
Thank you that's great.
