### ISSUE TITLE
Update user requirements

### ISSUE THREAD

**Issue by orhungorkem** [bounswe/2021SpringGroup3#39]
User requirements should be updated accroding to the feedbacks in the customer meeting.

**Comment by jcbod** [comment]
Updated User Requirements / Community:

- "Search" header changed as "Search & Filter".
- Added entries related to filtering (1.2.1.2. , 1.2.1.4. , 1.2.1.6. , 1.2.4.2.)
- "Follow" header changed as "Joining".
- Added an entry related to selecting a data type in posts (1.2.3.1.1).
- Added an entry related to creating new data types (1.2.3.5).
- Added references  to "System Requirements -> Searching / Filtering".

**Comment by orhungorkem** [comment]
Could you add a requirement about listing the data types in a community? In my scenario, it seems reasonable.

**Comment by jcbod** [comment]
Added: 
- **1.2.3.6.** Users shall be able to see data types that exist in a community as a list.

**Comment by irem-zeynep** [comment]
Updated User Requirements / Basics

- Added and edited entries related to the content of the profile page (1.1.4.2. , 1.1.4.4.).
-  Added entries related to the privacy setting of the profile page (1.1.4.6. , 1.1.4.7.).

Updated User Requirements / Community

- Added header about community creation (1.2.6).
- Added entries about creation, descriptive content, and the privacy setting of the community (1.2.6.1. , 1.2.6.2. , 1.2.6.3. , 1.2.6.4.). 
- Added an entry about sending community invitations (1.2.2.3.).

**Comment by halilbaydar** [comment]
I deleted the gest user roles and converted the common users to users.

**Comment by orhungorkem** [comment]
I reviewed and liked the updates, thanks.
