### ISSUE TITLE
Web: Create Deployment

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#395]
Please deploy our [web dev](https://github.com/bounswe/2021SpringGroup3/tree/web/dev) branch on Github pages, and share the link with the rest of the team to prepare for the presentation for Milestone 2.

Deadline: 14.11.2021

**Comment by jcbod** [comment]
Deployed our application to https://jcbod.github.io/my_app/.

**Comment by Ufuk-Arslan** [comment]
Looks nice, works properly. Thank you so much for your efforts mate!
