### ISSUE TITLE
Update System Requirements

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#40]
System Requirements should be updated based on the customer meeting.

**Deadline:** 18.04.2021

**Comment by bekirkeldal** [comment]
We are now discussing what to change. We will update the documentation after the meeting.

**Comment by kiymetakdemir** [comment]
We had some changes according to the customer meeting.

Notifications updated:
* 2.2.5
* 2.2.6
Community updated:
* 2.3.6
* 2.3.7
Search/Filter updated (sorting is added, data type is added as filtering choice):
* 2.4.2
* 2.4.3
* 2.4.4
* 2.4.5
* 2.4.4.3

Please review from the [requirements page](https://github.com/bounswe/2021SpringGroup3/wiki/Requirements).

**Comment by irem-zeynep** [comment]
Considering the feedbacks, it might be better if we use "join" instead of "follow" for the communities.

**Comment by bekirkeldal** [comment]
I have changed the requirements accordingly. You can check it [here](https://github.com/bounswe/2021SpringGroup3/wiki/Requirements).

**Comment by irem-zeynep** [comment]
I reviewed the System Requirements section. I think it is detailed and well organized. Thanks!

**Comment by kiymetakdemir** [comment]
I added categorization of search results (2.4.6.) as [Emre](https://github.com/bounswe/2021SpringGroup3/wiki/Abdurrahman-Emre-Yılmaz) suggested.
