### ISSUE TITLE
Mockup: Creating Community

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#41]
Prepare a mockup about creating a community in the web interface.

**Deadline:** 18.04.2021

**Comment by Ufuk-Arslan** [comment]
I've finished working on mockups for "Creating Community scenario" created by [Zeynep](https://github.com/bounswe/2021SpringGroup3/wiki/%C4%B0rem-Zeynep-Alag%C3%B6z), and updated wiki page for [scenario#1](https://github.com/bounswe/2021SpringGroup3/wiki/Scenario-%231:-Creating-Community#mockup).

**Comment by irem-zeynep** [comment]
It looks great, thank you!
