### ISSUE TITLE
Implementation for Web: Community Accept/Reject/Join/Leave/Kick Components

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#416]
We need to implement **Community Accept/Reject/Join/Leave/Kick Components** for our web application.

- [x] There should be a moderation tab next to the posts tab, for moderators of communities to see only.
- [x] Users shall be able to send a join request to moderators of communities
- [x] Moderators shall be able to accept or reject that request. 
- [x] Users shall be able to leave the communities they are in, 
- [x] Users shall be able to send a moderator role request to moderators of communities
- [x] Moderators shall be able to accept or reject that request. 
- [x] Moderators shall be able to kick members of their communities. 
- [x] Owners shall be able to delete the community.

Those services have already been implemented in our backend API and we can check out [Swagger documentation](https://github.com/bounswe/2021SpringGroup3/blob/backend/master/backend/resource/swagger.json) for more information. 

_A new branch for this feature shall be created. A pull request shall be opened and the work shall be reviewed before the merging process._

**Deadline**: 28.12.2021

**Comment by Ufuk-Arslan** [comment]
I have implemented the changes, please review #427

**Comment by irem-zeynep** [comment]
I reviewed and approved your implementation. Thanks

**Comment by Ufuk-Arslan** [comment]
The pull request has been reviewed and merged, now I'm closing this issue.
