### ISSUE TITLE
Scenario: Creating Community

### ISSUE THREAD

**Issue by jcbod** [bounswe/2021SpringGroup3#42]
Creating a scenario which involves a user creating a new community in the web interface.

**Comment by irem-zeynep** [comment]
We conducted a meeting on the details of the scenarios. I started documentation based on these outcomes.

**Comment by irem-zeynep** [comment]
I completed documenting details of the scenario except for the acceptance criteria part.  I will add that part after the requirements documentation is completed. You can check the current version [here](https://github.com/bounswe/2021SpringGroup3/wiki/Scenario-%231:-Creating-Community).

**Comment by irem-zeynep** [comment]
I completed the acceptance criteria part. Please review [Scenario 1](https://github.com/bounswe/2021SpringGroup3/wiki/Scenario-%231:-Creating-Community).

**Comment by jcbod** [comment]
Scenario looks great and does not need a revision. Issue closed.
