### ISSUE TITLE
Scenario: Posting Content

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#44]
Creating a scenario of a user posting content in the web interface.

**Comment by jcbod** [comment]
Initial scenario documentation finished and uploaded. The documentation can be found [here](https://github.com/bounswe/2021SpringGroup3/wiki/Scenario-%232:-Posting-Content).

**Comment by Ufuk-Arslan** [comment]
Nice work 😄
