### ISSUE TITLE
Scenario: Creating Data Type

### ISSUE THREAD

**Issue by kiymetakdemir** [bounswe/2021SpringGroup3#45]
Creating a scenario of a user creating a new data type in the web interface.

Deadline: 17.04.2021

**Comment by orhungorkem** [comment]
Okey, we planned the scenario details in the meeting and now I am documenting.

**Comment by orhungorkem** [comment]
I completed te scenario details except acceptance criteria. I am going to add it after the requirements are updated.

**Comment by orhungorkem** [comment]
With the updated requirements, I completed [Scenario 3](https://github.com/bounswe/2021SpringGroup3/wiki/Scenario-%233:-Creating-Data-Type). Please review.

**Comment by kiymetakdemir** [comment]
I reviewed your scenario. It is explained in detail and well structured. Thank you! Could you also enumerate the scenario steps please?

**Comment by orhungorkem** [comment]
OK, sure.

**Comment by kiymetakdemir** [comment]
Great work. Thank you!
