### ISSUE TITLE
Documenting the Frontend Meeting on 25.12.2021

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#451]
Documenting the key parts of the frontend meeting at 25.12.2021 and uploading the meeting notes to the wiki page.

**Comment by jcbod** [comment]
Documented the meeting and uploaded it to the wiki [here](https://github.com/bounswe/2021SpringGroup3/wiki/Frontend-Meeting-%233). Please review my work. Thanks in advance.

**Comment by Ufuk-Arslan** [comment]
I really liked the documentation. It will help us be more clear about our plans and tasks. Thanks m8, great job!
