### ISSUE TITLE
Implementation for Web: Viewing Comments In Posts

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#453]
We need to implement **Post Viewing Comments** for our web application. 

When a user clicks the comments button on a post to view its details, a user shall be able to see the list of comments under that post. This page is called `GetPostPage` in our application. For a single comment, users shall be able to see the username and the avatar of the user commenting, the text content, and the date of the comment. Upon clicking the commenter, users shall be redirected to that user's profile page. 

Those services have already been implemented in our backend API and we can check out [Swagger documentation](https://github.com/bounswe/2021SpringGroup3/blob/backend/master/backend/resource/swagger.json) for more information.

_A new branch for this feature shall be created. A pull request shall be opened and the work shall be reviewed before the merging process._

**Deadline**: 03.01.2022

**Comment by jcbod** [comment]
I implemented the required features and opened a pull request [here](https://github.com/bounswe/2021SpringGroup3/pull/491). Please review my work.

**Comment by Ufuk-Arslan** [comment]
I have reviewed and merged the PR. Now I'm closing this task. Thank you for your contribution.
