### ISSUE TITLE
Implementation for Web: Sending Comments In Posts

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#454]
We need to implement **Sending Comments In Posts** for our web application. 

After a user clicks the comments button on a post, they shall be able to send a new comment to that post on that post's detail page. If the comment is successfully sent, the user should be able to view the comment without reloading the page, if there were an error when sending the comment, they shall get an error message. You can check out `AboutCommunity` component which has an example for error handling.

Those services have already been implemented in our backend API and we can check out [Swagger documentation](https://github.com/bounswe/2021SpringGroup3/blob/backend/master/backend/resource/swagger.json) for more information.

_A new branch for this feature shall be created. A pull request shall be opened and the work shall be reviewed before the merging process._

**Deadline**: 03.01.2022

**Comment by jcbod** [comment]
I implemented the required features and opened a pull request [here](https://github.com/bounswe/2021SpringGroup3/pull/491). Please review my work.

**Comment by Ufuk-Arslan** [comment]
I have reviewed and merged the PR. Now I'm closing this task. Thank you for your contribution.
