### ISSUE TITLE
Implementation for Web: Post Like

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#455]
We need to implement **Post Like** for our web application. 

Users shall be able to like any post they can see. A user can like a post only once, and they can remove that if they want to. When a user likes a post/removes like, they should see the effect instantly.

Those services have already been implemented in our backend API and we can check out [Swagger documentation](https://github.com/bounswe/2021SpringGroup3/blob/backend/master/backend/resource/swagger.json) for more information.

_A new branch for this feature shall be created. A pull request shall be opened and the work shall be reviewed before the merging process._

**Deadline**: 03.01.2022

**Comment by jcbod** [comment]
I implemented the required features and opened a pull request [here](https://github.com/bounswe/2021SpringGroup3/pull/491). Please review my work.

**Comment by Ufuk-Arslan** [comment]
I have reviewed and merged the PR. Now I'm closing this task. Thank you for your contributions.
