### ISSUE TITLE
Scenario: Search & Filter

### ISSUE THREAD

**Issue by bekirkeldal** [bounswe/2021SpringGroup3#46]
Create a scenario of a user searching for a post using filtering mechanisms.

**Comment by kiymetakdemir** [comment]
We decided on main points of the scenario, now I am writing it in more detail.

**Comment by kiymetakdemir** [comment]
Scenario is documented at [wiki page](https://github.com/bounswe/2021SpringGroup3/wiki/Scenario-%234:-Searching-and-Filtering). Acceptance Criteria will be added later.

**Comment by kiymetakdemir** [comment]
Acceptance Criteria added.

**Comment by bekirkeldal** [comment]
I reviewed the scenario and everything seems fine. Good job!
