### ISSUE TITLE
Scenario: Profile Update

### ISSUE THREAD

**Issue by jcbod** [bounswe/2021SpringGroup3#47]
Creating a scenario where the user updates the details of their profile.

**Comment by bekirkeldal** [comment]
We decided on the scenario details in the meeting. I started working on the documentation.

**Comment by bekirkeldal** [comment]
I completed the documentation of [the scenario](https://github.com/bounswe/2021SpringGroup3/wiki/Scenario-%235:-Profile-Update). Please review it after the requirements are updated.

**Comment by jcbod** [comment]
Scenario looks great and does not need a revision. Issue closed.
