### ISSUE TITLE
Mockup: Search & Filter

### ISSUE THREAD

**Issue by halilbaydar** [bounswe/2021SpringGroup3#48]
A mockup should be prepared about the search filter in the mobile interface.

**Comment by emreboun** [comment]
Started to work on mobile mockups of  [User Scenario #4](https://github.com/bounswe/2021SpringGroup3/wiki/Scenario-%234:-Searching-and-Filtering)

**Comment by emreboun** [comment]
Mockups for Search & Filter in the mobile interface are designed and documented at [Scenario#4](https://github.com/bounswe/2021SpringGroup3/wiki/Scenario-%234:-Searching-and-Filtering) according to scenario written by [Kıymet](https://github.com/bounswe/2021SpringGroup3/wiki/K%C4%B1ymet-Akdemir).

**Comment by kiymetakdemir** [comment]
Thank you Emre! It seems elegant and consistent with the scenario. Just for the 5th step I think it is a bit ambiguous that if we sort or filter by date.

**Comment by Ufuk-Arslan** [comment]
Great work! Can you please include the scenario section before the mockups. Similar to [this page](https://github.com/bounswe/2021SpringGroup3/wiki/Scenario-%231:-Creating-Community). We want this so that all of the scenarios&mockups pages we crated are consistent to eachother.
