### ISSUE TITLE
Backend: Activity Stream Implementation

### ISSUE THREAD

**Issue by schroscatt** [bounswe/2021SpringGroup3#484]
[The necessary activities](https://www.w3.org/TR/activitystreams-vocabulary/#activity-types) should be stored in the Activity Stream format. 

Example:

{
    "@context": "https://www.w3.org/ns/activitystreams",
    "summary": "Sally accepted Joe into the club",
    "type": "Accept",
    "actor": {
      "type": "Person",
      "name": "Sally"
    },
    "object": {
      "type": "Person",
      "name": "Joe"
    },
    "target": {
      "type": "Group",
      "name": "The Club"
    }
  }

**Comment by irem-zeynep** [comment]
I [reviewed](https://github.com/bounswe/2021SpringGroup3/pull/483#pullrequestreview-841231455) and approved your implementation. Thanks 🚀
