### ISSUE TITLE
Mockup: Profile Update

### ISSUE THREAD

**Issue by halilbaydar** [bounswe/2021SpringGroup3#49]
A mockup should be prepared about user privacy in the mobile interface.

**Comment by kutaysaran** [comment]
completed to work on mobile mockups of [User Scenario #4](https://github.com/bounswe/2021SpringGroup3/wiki/Scenario-%235:-Profile-Update)

**Comment by Ufuk-Arslan** [comment]
Nice work! Can you please include the scenario section before the mockups. Similar to [this page](https://github.com/bounswe/2021SpringGroup3/wiki/Scenario-%231:-Creating-Community). We want this so that all of the scenarios&mockups pages we crated are consistent to eachother.

**Comment by kutaysaran** [comment]
included the scenario section before the mockup section.
