### ISSUE TITLE
Update glossary

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#50]
Glossary should be updated based on the customer meeting.

**Comment by irem-zeynep** [comment]
I prepared a new user roles hierarchy schema. 

**Glossary**
Deleted: "Guest User" 
Updated: "Post", "User" 

You can access the document from [here](https://github.com/bounswe/2021SpringGroup3/wiki/Requirements).

**Comment by orhungorkem** [comment]
**Glossary**  
Added: "Attributes "
Added: "Data type"

**Comment by irem-zeynep** [comment]
**Glossary**
Added: "Join"
Updated: "Follow"

**Comment by Ufuk-Arslan** [comment]
Looks great!

**Comment by irem-zeynep** [comment]
The glossary should be rearranged based on the feedback from the customer meeting 2.

**Comment by irem-zeynep** [comment]
I updated the user roles hierarchy schema.

**Glossary**
Deleted: "Community Creator"
Updated: "Community Moderator"

**Comment by orhungorkem** [comment]
**Glossary**  
Updated: "Block"
Added: "Mute"

**Comment by Ufuk-Arslan** [comment]
Looks nice!

**Comment by irem-zeynep** [comment]
[Glossary](https://github.com/bounswe/2021SpringGroup3/wiki/Requirements) is completed.
