### ISSUE TITLE
Mobile: Basic Post Search

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#500]
Users should be able to **search posts by their tags** without specifying the post type.

[Corresponding backend endpoint on the swagger](https://api.cmpegroupthree.store/docs/)

**Deadline**: 31.12.2021

_At least one team member from the mobile team should review the implementation. (📢 FYI @halilbaydar @kiymetakdemir)_

**Comment by Ufuk-Arslan** [comment]
The PR has been reviewed and merged. Now I'm closing this issue. Well done!
