### ISSUE TITLE
Designing Class Diagram

### ISSUE THREAD

**Issue by orhungorkem** [bounswe/2021SpringGroup3#52]
Could you design and document a comprehensive class diagram by classifying entities and determining boundaries among entities?

**Comment by irem-zeynep** [comment]
We decided on the necessary classes. We will meet tomorrow again to discuss relationships among them.

**Comment by kiymetakdemir** [comment]
We decided on the relations and distributed classes to fill the attributes and methods. We will meet on Sunday to review and discuss details.

**Comment by irem-zeynep** [comment]
We decided on the attributes and methods of the classes. You can access completed documentation from our corresponding Slack channel.  The documentation will be uploaded to the repository after review.

**Comment by orhungorkem** [comment]
We reviewed and liked the class diagram, you may upload it to the repository.
