### ISSUE TITLE
Mobile: Implementing Unlike Post Functionality

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#523]
**Unlike Post** functionality should be implemented. 

- Users should be able to unlike posts by pressing the like button a second time.
- Button color and number of likes should be updated based on the action.

Swagger documentation: [Unlike Post](https://api.cmpegroupthree.store/docs/#/Post%20Controller/unlike%20post)

**Deadline**: 3.01.2022

_At least one team member from the mobile team should review the implementation. (📢 FYI @halilbaydar @kiymetakdemir)_

**Comment by Ufuk-Arslan** [comment]
The PR has been merged and that closes this issue. Thanks!
