### ISSUE TITLE
Mobile: Passing Community ID to Post Detail

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#524]
Backend added `community id` field as a required field for _like post_ endpoints to check whether the user is a member of the community.

**Community id** should be passed to the **post detail component** and like **like post endpoint** as a parameter. It should be sent as a query param to the backend.

[Backend Swagger](https://api.cmpegroupthree.store/docs/#/)

**Deadline**: 3.01.2022

_At least one team member from the mobile team should review the implementation._

**Comment by Ufuk-Arslan** [comment]
The code looks clean, I approve this PR.

**Comment by irem-zeynep** [comment]
The [pull request](https://github.com/bounswe/2021SpringGroup3/pull/525) is reviewed and approved. The implementation is merged to the _mobile/dev_.
