### ISSUE TITLE
Mobile: Using Post Detail Component in Community Posts

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#526]
The post detail component has already been implemented.  #297

But the community posts component is not using this component. For this reason, it does not have new functionalities such as liking and commenting. 

The community posts should be improved to use the post detail component.

_At least one team member from the mobile team should review the implementation._

**Deadline**: 03.01.2022

**Comment by Ufuk-Arslan** [comment]
The PR has been merged, and now I'm closing this task. Thank you!
