### ISSUE TITLE
Backend: Adding sorting functionality to the advanced post search

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#529]
**Sorting functionality** should be added to the `advanced post search` in a community.
Posts should be sorted based on either **like count** (likeCount) or **date** (createdAt) in descending order. 

[Swagger Documentation for advanced post search](https://api.cmpegroupthree.store/docs/#/Post%20Controller/advance%20search%20posts)

**Deadline**: 2.01.2022

_At least one team member from the mobile team should review the implementation._

**Comment by Ufuk-Arslan** [comment]
The closing PR has been merged. Thanks!
