### ISSUE TITLE
Designing Use Case Diagram

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#54]
Use case diagram should be created to show the interaction between users and functions they may perform. This will help us have a better understanding of our project.

**Deadline:**  25.04.2021

**Comment by orhungorkem** [comment]
We conducted our meeting and decided on an outline. We are starting to work on diagram.

**Comment by orhungorkem** [comment]
We completed the diagram, you may see from slack. After review, we can upload to the repository.

**Comment by irem-zeynep** [comment]
Please update the use case diagram based on the notes we took during the meeting. You can access meeting notes from the corresponding Slack channel.

**Comment by halilbaydar** [comment]
I completed the use case diagram which is on me and updated the search and filter part according to the last decisions from the last team meeting.

**Comment by orhungorkem** [comment]
I added the following parts: 
*  Change password
*  Delete data type
*  Leave community
*  Seeing followed users in home page
*  Birthday info

**Comment by irem-zeynep** [comment]
The diagram is informative and well-designed. Thank you!
