### ISSUE TITLE
Updating Customer Meetings Documentation

### ISSUE THREAD

**Issue by bekirkeldal** [bounswe/2021SpringGroup3#57]
Please open a new page for documenting future customer meetings with our TA. Also edit the existing page accordingly.

**Comment by kiymetakdemir** [comment]
I documented notes of customer meeting 2 at [customer meetings page](https://github.com/bounswe/2021SpringGroup3/wiki/Customer-Meetings).

**Comment by irem-zeynep** [comment]
I documented customer meeting 1 notes. Please review.

**Comment by bekirkeldal** [comment]
Everything seems fine, good job!
