### ISSUE TITLE
Sequence Diagram: Search Community

### ISSUE THREAD

**Issue by orhungorkem** [bounswe/2021SpringGroup3#58]

**Comment by kiymetakdemir** [comment]
I designed a sequence diagram for searching a community. I will upload it to wiki page soon.

**Comment by kiymetakdemir** [comment]
Please review from [here](https://lucid.app/lucidchart/81218cb4-4213-4d6c-9f3b-739e0d53d88b/edit?viewport_loc=-330%2C-135%2C2382%2C1429%2C0_0&invitationId=inv_41175e06-45d5-425d-9bdd-588035086603).

**Comment by orhungorkem** [comment]
Thank you !

**Comment by kiymetakdemir** [comment]
I uploaded diagram to the [Sequence Diagrams](https://github.com/bounswe/2021SpringGroup3/wiki/Sequence-Diagrams).
