### ISSUE TITLE
Sequence Diagram: Private Message

### ISSUE THREAD

**Issue by kiymetakdemir** [bounswe/2021SpringGroup3#59]
Preparing a sequence diagram for private messaging.
**Deadline: 28.04.2021**

**Comment by halilbaydar** [comment]
I used the lucid website to draw the [diagram](https://lucid.app/publicSegments/view/449a82c9-eab2-46b8-9477-2f23861f24ba/image.png)

**Comment by kiymetakdemir** [comment]
Thank you!
