### ISSUE TITLE
Sequence Diagram: Report Comment

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#60]
Preparing a sequence diagram for reporting a comment under a post.
Deadline: 28.04.2021

**Comment by jcbod** [comment]
Comment reporting sequence diagram completed. Please review the diagram [here](https://lucid.app/lucidchart/ab91444a-57f6-4aa5-abe9-1019768dc23d/edit?shared=true&page=0_0#).

**Comment by Ufuk-Arslan** [comment]
Looks awesome, well done!
