### ISSUE TITLE
Sequence Diagram: Post content

### ISSUE THREAD

**Issue by halilbaydar** [bounswe/2021SpringGroup3#62]
Could you please draw a sequence diagram for posting content?

**Comment by Ufuk-Arslan** [comment]
Here is my [sequence diagram for posting content](https://lucid.app/lucidchart/4d462260-0a14-4b2d-a4eb-5c1cd76eaa8e/edit?viewport_l[…]1267%2C0_0&invitationId=inv_31770171-32d2-49f0-977e-3ea4102f1f99).

**Comment by halilbaydar** [comment]
Looks awesome, perfect job!
