### ISSUE TITLE
Sequence Diagram: Change Notification Settings

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#63]
Preparing a sequence diagram about changing notification settings.

**Deadline:** 28.04.2021

**Comment by schroscatt** [comment]
I completed the [sequence diagram](https://lucid.app/lucidchart/5516893e-1105-437e-b5a1-0945e91324e2/edit?viewport_l[…]C881%2C0_0&invitationId=inv_46ac2023-8d50-4023-80c9-263e719f8ec1).
Please review.

**Comment by irem-zeynep** [comment]
As far as I know, dashed lines represent the reply messages.  It would be better if you update the diagram accordingly.

**Comment by schroscatt** [comment]
Thank you for recognizing my mistake. The diagram is updated.

**Comment by irem-zeynep** [comment]
Thank you!
