### ISSUE TITLE
Status of Deliverables

### ISSUE THREAD

**Issue by orhungorkem** [bounswe/2021SpringGroup3#70]

**Comment by orhungorkem** [comment]
Please document the status of deliverables into Milestone Report 1.

**Comment by kiymetakdemir** [comment]
I started to prepare a table for list and status of deliverables.

**Comment by kiymetakdemir** [comment]
I prepared a table for list and status of deliverables and wrote evaluation of them. You can find it in our document shared in Slack.

**Comment by orhungorkem** [comment]
That's ok, thank you.
