### ISSUE TITLE
Documenting Table of Work Done by Each Member

### ISSUE THREAD

**Issue by Ufuk-Arslan** [bounswe/2021SpringGroup3#73]
You should find "Table of Work Done by Each Member" in the Milestone Report template shared in our slack workspace. There you should find your name and fill in the "Contributions" column.

**Comment by kiymetakdemir** [comment]
Everyone wrote their own contributions to the table. You can view from our [Project Plan](https://github.com/bounswe/2021SpringGroup3/blob/master/deliverables/CMPE%20352%20Milestone%20Report1.pdf).

**Comment by Ufuk-Arslan** [comment]
I reviewed it and it looks great. Now, I'm closing this issue. Good job everyone!
