### ISSUE TITLE
Uploading Class Diagram

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#74]
The class diagram should be uploaded to the corresponding [wiki page](https://github.com/bounswe/2021SpringGroup3/wiki/Class-Diagram) after finalizing the design. 

**Deadline:** 30.04.2021 11:00 pm

**Comment by halilbaydar** [comment]
Could you please add the communicationChannel class the following functions:

* getAllChats() // returns all communications channels
* getMessages(Page) // returns the page of messages according to the given page
* senMessage()
* seen()
* receiveMessage() // authomatically triggered by server if other user is in the same channel
* sent() // authomatically triggered by server when the message is saved to db

**Comment by jcbod** [comment]
- getChatList():list<CommunicationChannel> already exists under the User and provides the necessary functionality for getAllChats().
- Added seen() under CommunicationChannel.
- Added receiveMessage() under CommunicationChannel.
- Added sent() under CommunicationChannel.

Can you explain what is the Page parameter in the getMessages() function? We do not have such a class in our class diagram.

**Comment by halilbaydar** [comment]
Sorry I couldn't see the getAllChats() function in the diagram. 
The page parameter is a sign which gives information for which part of the messages of the channel should be requested from the server. You don't need to do an extra thing for it, it is just an integer value.
