### ISSUE TITLE
Filling in the Responsibility Assignment Matrix (RAM)

### ISSUE THREAD

**Issue by schroscatt** [bounswe/2021SpringGroup3#75]
Please fill in the responsibility assignment matrix (RAM) according to previous issues and tasks.

**Comment by irem-zeynep** [comment]
We completed the [RAM](https://github.com/bounswe/2021SpringGroup3/wiki/Responsibility-Assignment-Matrix-(RAM)). Please review.

**Comment by schroscatt** [comment]
It is awesome! Thank you!
