### ISSUE TITLE
Deciding the name 

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#78]
We should find a name for our app and website.  Please write your suggestions.

**Comment by kiymetakdemir** [comment]
I don't have a name suggestion for now but if we would like to emphasize on the data types, we can find a new name for data types then we derive app name from there. Like we call posts as 'Tweet' and the app name is 'Twitter'. Emphasizing on the communities is also ok.

**Comment by halilbaydar** [comment]
Bounity

**Comment by Ufuk-Arslan** [comment]
Could you please rate these names [here](https://forms.gle/gZ2i1WxvGyuQsewC8).

**Comment by Ufuk-Arslan** [comment]
We have decided the name as **Boxy**, hurrahhh!!
