### ISSUE TITLE
Implement API functionality : Get community by name

### ISSUE THREAD

**Issue by orhungorkem** [bounswe/2021SpringGroup3#83]
Please implement the function to get community by name.

**Comment by bekirkeldal** [comment]
I finished the implementation of the functionality. Please review it from [here](https://github.com/bounswe/2021SpringGroup3/pull/111).

**Comment by kiymetakdemir** [comment]
[Ufuk](https://github.com/bounswe/2021SpringGroup3/wiki/Ufuk-Arslan) and I reviewed. Good job!
