### ISSUE TITLE
Implement API functionality : Create Post

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#85]
Create Post API should be implemented.

**Deadline:** 30.05.2021, 23.59

**Comment by orhungorkem** [comment]
I am working on it.

**Comment by orhungorkem** [comment]
I completed my implementation and opened a pull request for review.

**Comment by irem-zeynep** [comment]
[The request](https://github.com/bounswe/2021SpringGroup3/pull/101) is approved and merged to the **dev** branch.
