### ISSUE TITLE
Implement API functionality: Getting Post by a Community 

### ISSUE THREAD

**Issue by irem-zeynep** [bounswe/2021SpringGroup3#95]
The API that fetches posts of the selected community should be implemented.

**Deadline:** 30.05.2021, 23.59

**Comment by kiymetakdemir** [comment]
I implemented the functionality and created a [pull request](https://github.com/bounswe/2021SpringGroup3/pull/100).

**Comment by irem-zeynep** [comment]
The [request](https://github.com/bounswe/2021SpringGroup3/pull/100) is approved and merged to the **dev** branch.
